### PR TITLE
Slight reduction in size

### PR DESCRIPTION
**Pull request by 0x21D8**
All compression algorithms are lossless except for alpha channel, in alpha channel all colour values of fully transparent pixels have been changed, which is technically lossy but impossible to notice except in some rare cases. Please let me know if the alpha channel modification is inappropriate and I'll change it.

### CODE REVIEW

**Comment by erosman** [comment]
TBH, the reduction is size in insignificant.
Furthermore, these images do not belong to me so I thought it would be better to keep them untouched.

**Comment by 0x21D8** [comment]
> TBH, the reduction is size in insignificant. Furthermore, these images do not belong to me so I thought it would be better to keep them untouched.

It's insignificant because of the original size of the images AND because it's lossless compression. Lossless compression should be legal. It doesn't change anything about the logo itself, and the alpha channel is just a colour space, **it's a simple shape, or one that's commonly used, so it can't be copyrighted on its own**. If you don't really understand how the lossless compression algorithm works.

**Comment by 0x21D8** [comment]
It would be really nice if you would think about merging this, not because of the "insignificance", (personally, and I hope not only for me, I find this significant enough) but because of the principle of minimalism, since it is intended as "Super Lightweight". and every free bit is actually nice to have. Later I will try to do something with svg and there will be much more saving, so in optimisation you have to start with something, starting from the simplest and most primitive things to the most complex, and if you really care, then I don't even need to explain other reasons.

**Comment by erosman** [comment]
If they could be made into SVG, that would be great.

**Pull request merged**
